[tool.poetry]
name = "voice100"
version = "1.3.2"
description = "Voice100 is a small TTS for English and Japanese."
authors = ["Katsuya Iida <katsuya.iida@gmail.com>"]
license = "mit"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.13.1"
torchaudio = "^0.13.0"
pytorch_lightning = ">=1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
