[tool.poetry]
name = "voice100"
version = "1.3.2"
description = "Voice100 is a small TTS for English and Japanese."
authors = ["Katsuya Iida <katsuya.iida@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
torch = "^1.13.1"
torchaudio = "^0.13.0"
pytorch_lightning = ">=1.4.0"
fugashi = {extras = ["lang-ja"], version = "^1.2.1"}
unidic-lite = {extras = ["lang-ja"], version = "^1.0.8"}
pyworld = {extras = ["tts"], version = "^0.3.2"}
g2p-en = {extras = ["lang-en-phone"], version = "^2.1.0"}

[tool.poetry.group.test]  # This part can be left out

[tool.poetry.group.test.dependencies]
pytest = "^6.0.0"
flake8 = "^6.0.0"
soundfile = "^0.11.0"
onnxruntime = "^1.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
