seed_everything: 1234
trainer:
  max_epochs: 100
  gradient_clip_val: 1.0
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        save_last: true
        every_n_epochs: 10
model:
  class_path: voice100.models.AudioToAlignText
  init_args:
    vocab_size: 29
    audio_size: 64
    encoder_settings:
      - [512, false, 5, 1, 2, false]
      - [512, false, 5, 2, 2, false]
      - [512, false, 5, 1, 2, false]
      - [512, false, 5, 1, 2, false]
    decoder_num_layers: 2
    decoder_hidden_size: 512
    learning_rate: 1e-3
data:
  class_path: voice100.data_modules.AudioTextDataModule
  init_args:
    vocoder: mel
    dataset: ljspeech,librispeech
    language: en
    sample_rate: 16000
    use_align: false
    use_phone: false
    batch_size: 64
